import os

def build(bld):
    if os.name == 'nt':
        raise NotImplementedError("Check for wincrypt stuff")
        raise NotImplementedError("Check for mingw time workaround stuff")
    # FIXME: there has to be a better way to refer to numpy/core include
    includes = [
            os.path.join(bld.srcnode.path_from(bld.path), "numpy/core"),
            os.path.join(bld.srcnode.path_from(bld.path), "numpy/core/include"),
            os.path.join(bld.srcnode.path_from(bld.path), "numpy/core/include/numpy"),
            os.path.join(bld.srcnode.path_from(bld.path), "numpy/core/src/private")]

    source = [os.path.join('mtrand', x) for x in 
              ['mtrand.c', 'randomkit.c', 'initarray.c', 'distributions.c']]

    bld(features="c cshlib pyext",
        target="mtrand",
        source=source,
        includes=includes)
